//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class celebrations {
    
    private celebrationsRepetative[] repetativeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("repetative")]
    public celebrationsRepetative[] repetative {
        get {
            return this.repetativeField;
        }
        set {
            this.repetativeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class celebrationsRepetative {
    
    private string instrumentField;
    
    private decimal musicantsField;
    
    private decimal personsField;
    
    private decimal happinessField;
    
    /// <remarks/>
    public string instrument {
        get {
            return this.instrumentField;
        }
        set {
            this.instrumentField = value;
        }
    }
    
    /// <remarks/>
    public decimal musicants {
        get {
            return this.musicantsField;
        }
        set {
            this.musicantsField = value;
        }
    }
    
    /// <remarks/>
    public decimal persons {
        get {
            return this.personsField;
        }
        set {
            this.personsField = value;
        }
    }
    
    /// <remarks/>
    public decimal happiness {
        get {
            return this.happinessField;
        }
        set {
            this.happinessField = value;
        }
    }
}
